repos:
-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-docstrings]
        types: [python]
        files: \.(py)$
        exclude: ^(venv/|\.env/|\.venv/|env/)